import { AD } from '../ad';
import { AI } from '../ai';
import { AL } from '../al';
import { AR } from '../ar';
import { AT } from '../at';
import { AU } from '../au';
import { AZ } from '../az';
import { BA } from '../ba';
import { BE } from '../be';
import { BG } from '../bg';
import { BO } from '../bo';
import { BR } from '../br';
import { BY } from '../by';
import { BZ } from '../bz';
import { CA } from '../ca';
import { CH } from '../ch';
import { CL } from '../cl';
import { CN } from '../cn';
import { CO } from '../co';
import { CR } from '../cr';
import { CU } from '../cu';
import { CY } from '../cy';
import { CZ } from '../cz';
import { DE } from '../de';
import { DK } from '../dk';
import { DO } from '../do';
import { DZ } from '../dz';
import { EC } from '../ec';
import { EE } from '../ee';
import { EG } from '../eg';
import { ES } from '../es';
import { FI } from '../fi';
import { FO } from '../fo';
import { FR } from '../fr';
import { GB } from '../gb';
import { GH } from '../gh';
import { GN } from '../gn';
import { GR } from '../gr';
import { GT } from '../gt';
import { HK } from '../hk';
import { HR } from '../hr';
import { HU } from '../hu';
import { ID } from '../id';
import { IE } from '../ie';
import { IL } from '../il';
import { IN } from '../in';
import { IS } from '../is';
import { IT } from '../it';
import { JP } from '../jp';
import { KE } from '../ke';
import { KR } from '../kr';
import { LI } from '../li';
import { LT } from '../lt';
import { LU } from '../lu';
import { LV } from '../lv';
import { MA } from '../ma';
import { MC } from '../mc';
import { MD } from '../md';
import { ME } from '../me';
import { MK } from '../mk';
import { MT } from '../mt';
import { MU } from '../mu';
import { MX } from '../mx';
import { MY } from '../my';
import { NL } from '../nl';
import { NO } from '../no';
import { NZ } from '../nz';
import { PE } from '../pe';
import { PK } from '../pk';
import { PL } from '../pl';
import { PT } from '../pt';
import { PY } from '../py';
import { RO } from '../ro';
import { RS } from '../rs';
import { RU } from '../ru';
import { SE } from '../se';
import { SG } from '../sg';
import { SI } from '../si';
import { SK } from '../sk';
import { SM } from '../sm';
import { SV } from '../sv';
import { TH } from '../th';
import { TN } from '../tn';
import { TR } from '../tr';
import { TW } from '../tw';
import { UA } from '../ua';
import { US } from '../us';
import { UY } from '../uy';
import { VE } from '../ve';
import { VN } from '../vn';
import { ZA } from '../za';

export type StdnumEnum = {
  AD: AD;
  AI: AI;
  AL: AL;
  AR: AR;
  AT: AT;
  AU: AU;
  AZ: AZ;
  BA: BA;
  BE: BE;
  BG: BG;
  BO: BO;
  BR: BR;
  BY: BY;
  BZ: BZ;
  CA: CA;
  CH: CH;
  CL: CL;
  CN: CN;
  CO: CO;
  CR: CR;
  CU: CU;
  CY: CY;
  CZ: CZ;
  DE: DE;
  DK: DK;
  DO: DO;
  DZ: DZ;
  EC: EC;
  EE: EE;
  EG: EG;
  ES: ES;
  FI: FI;
  FO: FO;
  FR: FR;
  GB: GB;
  GH: GH;
  GN: GN;
  GR: GR;
  GT: GT;
  HK: HK;
  HR: HR;
  HU: HU;
  ID: ID;
  IE: IE;
  IL: IL;
  IN: IN;
  IS: IS;
  IT: IT;
  JP: JP;
  KE: KE;
  KR: KR;
  LI: LI;
  LT: LT;
  LU: LU;
  LV: LV;
  MA: MA;
  MC: MC;
  MD: MD;
  ME: ME;
  MK: MK;
  MT: MT;
  MU: MU;
  MX: MX;
  MY: MY;
  NL: NL;
  NO: NO;
  NZ: NZ;
  PE: PE;
  PK: PK;
  PL: PL;
  PT: PT;
  PY: PY;
  RO: RO;
  RS: RS;
  RU: RU;
  SE: SE;
  SG: SG;
  SI: SI;
  SK: SK;
  SM: SM;
  SV: SV;
  TH: TH;
  TN: TN;
  TR: TR;
  TW: TW;
  UA: UA;
  US: US;
  UY: UY;
  VE: VE;
  VN: VN;
  ZA: ZA;
};
